#### 1850200-黄天洋-第十周实验课-申优
# 实践课10
## 1&emsp;内容
#### 1.2&emsp;Jacobi迭代法（向量化&emsp;$\dfrac{||b-Ax_k||}{||b||}<\epsilon$）

In [1]:
import numpy as np
from numpy.linalg import inv, norm

#Jacobi迭代法-向量化情况
#A为系数矩阵，b为右端向量，eps为控制精度，K为最大迭代次数
def Jacobi(A,b,eps,K):
    D=np.diag(np.diag(A))
    U=(D-np.triu(A))
    L=(D-np.tril(A))
    M=inv(D)
    err=1
    errs=list()
    step=0
    x=np.zeros(len(b))
    while err>eps and step<K:
        x=np.dot(np.dot(M,L+U),x)+np.dot(M,b)
        err=norm(b-np.dot(A,x))/norm(b)
        errs.append(err)
        step=step+1
    return [x,step]

#例-解方程
A=np.mat('5 -2 3;-3 9 1;2 -1 -7')
b=np.array([14,10,-3])
eps=10**-5
[x,step]=Jacobi(A,b,eps,1000)
print('方程的解为：',x,'迭代次数为：',step)

方程的解为： [2.99999154 2.00000699 1.00000728] 迭代次数为： 9


#### 1.2&emsp;Jacobi迭代法（未向量化&emsp;$\dfrac{||x_{k+1}-x_k||}{||x_{k+1}||}<\epsilon$）

In [90]:
import numpy as np
from numpy.linalg import inv, norm

#Jacobi迭代法-向量化情况
#A为系数矩阵，b为右端向量，eps为控制精度，K为最大迭代次数
def Jacobi_uv(A,b,eps,K):
    err=1
    errs=list()
    step=0
    l=len(b)
    x=np.zeros(l)
    while err>eps and step<K:
        y=np.zeros(l)
        for i in range(l):
            y[i]=1/A[i,i]*(b[i]-np.dot(A[i,:],x)+A[i,i]*x[i])
        err=norm(y-x)/norm(y)
        x=y
        step=step+1
    return [x,step]

#例-解方程
A=np.mat('5 -2 3;-3 9 1;2 -1 -7')
b=np.array([14,10,-3])
eps=10**-5
[x,step]=Jacobi_uv(A,b,eps,1000)
print('方程的解为：',x,'迭代次数为：',step)

方程的解为： [2.99999154 2.00000699 1.00000728] 迭代次数为： 9


#### 2.&emsp;Gauss-Seidel迭代法

In [91]:
import numpy as np
from numpy.linalg import inv, norm

#Gauss-Seidel迭代法
#A为系数矩阵，b为右端向量，eps为控制精度，K为最大迭代次数
def GS(A,b,eps,K):
    D=np.diag(np.diag(A))
    U=(D-np.triu(A))
    L=(D-np.tril(A))
    M=inv(D-L)
    err=1
    errs=list()
    step=0
    x=np.zeros(len(b))
    while err>eps and step<K:
        x=np.dot(np.dot(M,U),x)+np.dot(M,b)
        err=norm(b-np.dot(A,x))/norm(b)
        errs.append(err)
        step+=1
    return [x,step]

#例-解方程
A=np.mat('5 -2 3;-3 9 1;2 -1 -7')
b=np.array([14,10,-3])
eps=10**-5
[x,step]=GS(A,b,eps,1000)
print('方程的解为：',x,'迭代次数为：',step)

方程的解为： [3.00000851 2.00000419 1.00000183] 迭代次数为： 6


#### 3.&emsp;SOR迭代法

In [92]:
import numpy as np
from numpy.linalg import inv, norm

#SOR迭代法
#A为系数矩阵，b为右端向量，w为松弛因子，eps为控制精度，K为最大迭代次数
def SOR(A,b,w,eps,K):
    D=np.diag(np.diag(A))
    U=(D-np.triu(A))
    L=(D-np.tril(A))
    M=inv(D-w*L)
    err=1
    errs=list()
    step=0
    x=np.zeros(len(b))
    while err>eps and step<K:
        x=np.dot(np.dot(M,(1-w)*D+w*U),x)+w*np.dot(M,b)
        err=norm(b-np.dot(A,x))/norm(b)
        errs.append(err)
        step+=1
    return [x,step]

#例-解方程（取松弛因子w=0.8）
A=np.mat('5 -2 3;-3 9 1;2 -1 -7')
b=np.array([14,10,-3])
eps=10**-5
[x,step]=SOR(A,b,0.8,eps,1000)
print('方程的解为：',x,'迭代次数为：',step)

方程的解为： [3.00001409 2.0000084  1.00000438] 迭代次数为： 9


## 2&emsp;练习
#### 1.&emsp;分别用Jacobi迭代法，Gauss-Seidel迭代法，SOR迭代法求解线性方程
$$\begin{cases}
x_1-\dfrac14x_3-\dfrac14x_4=\dfrac12 
\\ x_2-\dfrac14x_3-\dfrac14x_4=\dfrac12 
\\ -\dfrac14x_1-\dfrac14x_2+x_3=\dfrac12
\\ -\dfrac14x_1-\dfrac14x_2+x_4=\dfrac12
\end{cases} $$
#### 并计算相应迭代矩阵的谱半径，停止迭代条件为$\frac{||b-Ax_k||}{||b||}<1\times10^{-5}$

In [93]:
#运行本程序前请先运行内容中的三个函数
import numpy as np
from numpy.linalg import inv,norm,eig

#定义系数矩阵A和右端向量b
A=np.mat('1,0,-0.25,-0.25;0,1,-0.25,-0.25;-0.25,-0.25,1,0;-0.25,-0.25,0,1')
b=np.array([1/2,1/2,1/2,1/2])
eps=10**-5
K=1000
D=np.diag(np.diag(A))
L=(D-np.tril(A))
U=(D-np.triu(A))

#Jacobi迭代法
B_J=np.dot(inv(D),D-A)
l_J=np.max(np.abs(eig(B_J)[0]))
[x,step]=Jacobi_uv(A,b,eps,1000)
print('Jacobi迭代法的解为',x,'迭代次数为',step,'谱半径为',l_J)

#Gauss-Seidel迭代法
B_GS=np.dot(inv(D-L),D-L-A)
l_GS=np.max(np.abs(eig(B_GS)[0]))
[x,step]=GS(A,b,eps,1000)
print('Gauss-Seidel迭代法的解为',x,'迭代次数为',step,'谱半径为',l_GS)

#SOR迭代法，取w=1.1
w=1.1
B_SOR=np.dot(inv(D-w*L),(1-w)*D+w*U)
l_SOR=np.max(np.abs(eig(B_SOR)[0]))
[x,step]=SOR(A,b,w,eps,1000)
print('SOR迭代法的解为',x,'迭代次数为',step,'谱半径为',l_SOR)

Jacobi迭代法的解为 [0.99999237 0.99999237 0.99999237 0.99999237] 迭代次数为 17 谱半径为 0.49999999999999994
Gauss-Seidel迭代法的解为 [0.99999237 0.99999237 0.99999619 0.99999619] 迭代次数为 9 谱半径为 0.25
SOR迭代法的解为 [0.99999941 0.99999941 0.9999991  0.9999991 ] 迭代次数为 6 谱半径为 0.10000000000000007


#### 2.&emsp;用Jacobi迭代法，Gauss-Seidel迭代法求解线性方程
$$    \left(
    \begin{array}{ccc}
     5& -2  &3 \\
     -3& 9  &1 \\
     2& -1  &-7 \\
    \end{array} \right)
    \left(
        \begin{array}{c}
         x_1\\
         x_2\\
         x_3\\
        \end{array} \right)=
    \left(
    \begin{array}{c}
     14\\
     10\\
     -3\\
    \end{array} \right)$$
#### &emsp;&emsp;停止迭代条件为$\frac{||x_{k+1}-x_k||}{||x_{k+1}||}<1\times10^{-5}$

In [94]:
#运行本程序前请先运行内容中的三个函数
import numpy as np
from numpy.linalg import inv,norm

#定义系数矩阵A和右端向量b
A=np.mat('5,-2,3;-3,9,1;2,-1,-7')
b=np.array([14,10,-3])
eps=10**-5
K=1000

#Jacobi迭代法
[x,step]=Jacobi(A,b,eps,K)
print('Jacobi迭代法的解为',x,'迭代次数为',step)

#Gauss-Seidel迭代法
[x,step]=GS(A,b,eps,K)
print('Gauss-Seidel迭代法的解为',x,'迭代次数为',step)

Jacobi迭代法的解为 [2.99999154 2.00000699 1.00000728] 迭代次数为 9
Gauss-Seidel迭代法的解为 [3.00000851 2.00000419 1.00000183] 迭代次数为 6


#### 3.&emsp;用如下迭代格式
$$x_{k+1}=x_k+\frac1{||A||_2}(b-Ax_k)$$
#### &emsp;&emsp;求解线性方程组$Ax=b$，其中
$$A=\left(
    \begin{array}{ccc}
     1& 1  &2 \\
     1& 2  &1 \\
     2& 1  &10 \\
    \end{array} \right),
   b=\left(
     \begin{array}{c}
     1\\
     3\\
     5\\
    \end{array} \right)$$
#### &emsp;&emsp;停止迭代条件为$\frac{||x_{k+1}-x_k||}{||x_{k+1}||}<1\times10^{-5}$

In [95]:
import numpy as np
from numpy.linalg import norm

#定义系数矩阵A和右端向量b
A=np.array([[1,1,2],[1,2,1],[2,1,10]])
b=np.array([1,3,5])

#迭代
err=1
x=np.zeros(len(b))
step=0
while err>10**-5:
    x=x+1/norm(A)*(b-np.dot(A,x))
    step=step+1
    err=norm(b-np.dot(A,x))/norm(b)
print('方程的解为',x,'迭代次数为',step)

方程的解为 [-3.99975716  2.99988519  0.9999621 ] 迭代次数为 489


## 3&emsp;作业
#### **1.&emsp;Jacobi迭代法**
实验目的：Jacobi迭代法<br/>
实验内容：编写一个Jacobi迭代法程序以求解线性代数方程组$Ax=b$,其中$b$为纯$1$向量。系数矩阵$A=(a_{n,m})$的阶数$N=(N_x+1)(N_y+1)$，其中$N_x$和$N_y$为正整数；其元素按如下方式确定：对于任意正整数$n=1,2,\dots,N$，有
$$a_{n,m}=
\begin{cases} 
   -4&  m=n
\\ -1&  m=n-(N_x+1)& m>0
\\ -1&  m=n+(N_x+1)& m>0
\\ -1&  m=n-1 & m>0
\\ -1&  m=n+1 & m>0
\\  0&  \text{其他}
\end{cases} $$
要求程序以$N_x$和$N_y$，最大迭代步数$K$和控制精度$\epsilon$为输入参数；停止迭代条件为$\frac{||b-Ax_k||}{||b||}<\epsilon$

In [1]:
import numpy as np
from numpy.linalg import inv, norm

#Jacobi迭代法求解本题的Ax=b
def Jacobi_N(Nx,Ny,eps,K):
    N=(Nx+1)*(Ny+1)
    b=np.ones(N)
    A=np.zeros((N,N))
    for m in range(N):
        for n in range(N):
            if n==m:
                A[m,n]=-4
            elif m==n-(Nx+1) or m==n+(Nx+1) or m==n-1 or m==n+1:
                A[m,n]=-1
    D=np.diag(np.diag(A))
    U=(D-np.triu(A))
    L=(D-np.tril(A))
    M=inv(D)
    err=1
    errs=list()
    step=0
    x=np.zeros(len(b))
    while err>eps and step<K:
        x=np.dot(np.dot(M,L+U),x)+np.dot(M,b)
        err=norm(b-np.dot(A,x))/norm(b)
        errs.append(err)
        step=step+1
    return A,b,x,step

#输入参数
Nx=2
Ny=2
eps=10**-5
K=1000
A,b,x,step=Jacobi_N(Nx,Ny,eps,K)
print('Nx=',Nx,'，Ny=',Ny,'时，解为',x,'迭代次数为',step)
print(A)

Nx= 2 ，Ny= 2 时，解为 [-0.20783021 -0.10843312 -0.19276933 -0.06024014 -0.16566041 -0.06024014
 -0.19276933 -0.10843312 -0.20783021] 迭代次数为 58
[[-4. -1.  0. -1.  0.  0.  0.  0.  0.]
 [-1. -4. -1.  0. -1.  0.  0.  0.  0.]
 [ 0. -1. -4. -1.  0. -1.  0.  0.  0.]
 [-1.  0. -1. -4. -1.  0. -1.  0.  0.]
 [ 0. -1.  0. -1. -4. -1.  0. -1.  0.]
 [ 0.  0. -1.  0. -1. -4. -1.  0. -1.]
 [ 0.  0.  0. -1.  0. -1. -4. -1.  0.]
 [ 0.  0.  0.  0. -1.  0. -1. -4. -1.]
 [ 0.  0.  0.  0.  0. -1.  0. -1. -4.]]


In [2]:
import numpy as np
np.diag(np.array([4,4,4]))+np.diag(np.array([1,1]),1)+np.diag(np.array([1,1]),-1)

array([[4, 1, 0],
       [1, 4, 1],
       [0, 1, 4]])

#### **2.&emsp;Gauss-Seidel迭代法**
实验目的：Gauss-Seidel迭代法<br/>
实验内容：编写一个Gauss-Seidel迭代法程序以求解线性代数方程组$Ax=b$，其中右端向量$b=(b_j)_{N\times 1}$和系数矩阵$A=(a_{m,n})$由下式确定
$$a_{i,j}=
\begin{cases} 
   i^2&  i=j
\\ \frac1{i+j+1}& i\not=j
\end{cases},b_j=j,\forall i,j=1,2,\dots,N$$
要求程序以$N$，最大迭代步数$K$和控制精度$\epsilon$为输入参数，停止迭代条件为$\frac{||b-Ax_k||}{||b||}<\epsilon$

In [97]:
import numpy as np
from numpy.linalg import inv, norm

#Gauss-Seidel迭代法求解本题Ax=b
def GS_N(N,eps,K):
    A=np.zeros((N,N))
    b=np.zeros(N)
    for i in range(N):
        for j in range(N):
            if i==j:
                A[i,j]=(i+1)**2
            else:
                A[i,j]=1/(i+j+3)
    for j in range(N):
        b[j]=j+1
    D=np.diag(np.diag(A))
    U=(D-np.triu(A))
    L=(D-np.tril(A))
    M=inv(D-L)
    err=1
    errs=list()
    step=0
    x=np.zeros(len(b))
    while err>eps and step<K:
        x=np.dot(np.dot(M,U),x)+np.dot(M,b)
        err=norm(b-np.dot(A,x))/norm(b)
        errs.append(err)
        step+=1
    return A,b,x,step

#输入参数
N=5
eps=10**-5
K=1000
A,b,x,step=GS_N(N,eps,K)
print('N=',N,'时，解为',x,'迭代次数为',step)

N= 5 时，解为 [0.7667374  0.42510616 0.30280265 0.23465686 0.1912087 ] 迭代次数为 4


#### **3.&emsp;SOR迭代法**
实验目的：SOR迭代法<br/>
实验内容：<br/>
(1)编写一个SOR迭代法以求解第1题中的线性方程组，要求程序以$N_x$和$N_y$，最大迭代步数$K$和控制精度$\epsilon$为输入参数，停止迭代条件为$\frac{||b-Ax_k||}{||b||}<\epsilon$<br/>
(2) 令$N_x=N_y=30,K=2000,\epsilon=1\times 10^{-5}$，分别取松弛因子$\omega=0,0.1,0.2,\dots,1.9,2$进行计算，记录SOR迭代法的迭代步数，并给出最优松弛因子

In [98]:
import numpy as np
from numpy.linalg import inv, norm

#SOR迭代法求解本题的Ax=b
def SOR_N(Nx,Ny,w,eps,K):
    N=(Nx+1)*(Ny+1)
    b=np.ones(N)
    A=np.zeros((N,N))
    for m in range(N):
        for n in range(N):
            if n==m:
                A[m,n]=-4
            elif m==n-(Nx+1) or m==n+(Nx+1) or m==n-1 or m==n+1:
                A[m,n]=-1
    D=np.diag(np.diag(A))
    U=(D-np.triu(A))
    L=(D-np.tril(A))
    M=inv(D-w*L)
    err=1
    errs=list()
    step=0
    x=np.zeros(len(b))
    while err>eps and step<K:
        x=np.dot(np.dot(M,(1-w)*D+w*U),x)+w*np.dot(M,b)
        err=norm(b-np.dot(A,x))/norm(b)
        errs.append(err)
        step+=1
    return A,b,x,step

#输入参数
Nx=30
Ny=30
eps=10**-5
K=2000
w=np.linspace(0,2,21)
for i in range(21):
    A,b,x,step=SOR_N(Nx,Ny,w[i],eps,K)
    print('w=',w[i],'时，迭代次数为',step)

#最优松弛因子
A,b,x,step=SOR_N(30,30,1.7,10**-5,2000)
print('可得w=1.7为最优松弛因子，解为',x,'迭代次数为',step)

w= 0.0 时，迭代次数为 2000
w= 0.1 时，迭代次数为 2000
w= 0.2 时，迭代次数为 2000
w= 0.30000000000000004 时，迭代次数为 1895
w= 0.4 时，迭代次数为 1338
w= 0.5 时，迭代次数为 1003
w= 0.6000000000000001 时，迭代次数为 781
w= 0.7000000000000001 时，迭代次数为 622
w= 0.8 时，迭代次数为 502
w= 0.9 时，迭代次数为 409
w= 1.0 时，迭代次数为 335
w= 1.1 时，迭代次数为 275
w= 1.2000000000000002 时，迭代次数为 224
w= 1.3 时，迭代次数为 181
w= 1.4000000000000001 时，迭代次数为 145
w= 1.5 时，迭代次数为 113
w= 1.6 时，迭代次数为 86
w= 1.7000000000000002 时，迭代次数为 63
w= 1.8 时，迭代次数为 77
w= 1.9000000000000001 时，迭代次数为 160
w= 2.0 时，迭代次数为 2000
可得w=1.7为最优松弛因子，解为 [-0.1973603  -0.12560047 -0.15647911 -0.14089651 -0.14987942 -0.14414059
 -0.14810131 -0.14520248 -0.14742436 -0.1456554  -0.1471108  -0.14587711
 -0.14695294 -0.14598823 -0.14687792 -0.14603366 -0.14685841 -0.14602874
 -0.14688822 -0.1459715  -0.14697806 -0.14584013 -0.14716582 -0.14557103
 -0.14755967 -0.14497249 -0.14852109 -0.1433058  -0.15171904 -0.13633641
 -0.1692814  -0.0849608  -0.14377036 -0.10758728 -0.13006736 -0.11544631
 -0.12546883 -0.11825271 -0.1236765