In [1]:
#第1题
import numpy as np
e1=np.arange(0,10,1)
print(e1)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
#第2题
e2=np.zeros((3,3))==np.zeros((3,3))
print(e2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [3]:
#第3题
e3=np.arange(9).reshape((3,3))
print(e3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
#第4题
a=np.array([1,2,0,0,4,0])
e4=np.where(a!=0)
print(e4[0])

[0 1 4]


In [5]:
#第5题
e5=np.array([0,1,2,3,4,5,6,7,8,9])
e5=(e5[e5%2==1])
print(e5)

[1 3 5 7 9]


In [6]:
#第6题
e6=np.array([0,1,2,3,4,5,6,7,8,9])
e6[e6%2==1]=-1
print(e6)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [7]:
#第7题
temp=np.array([0,1,2,3,4,5,6,7,8,9])
e7=temp.copy()
e7[e7%2==1]=-1
print('original array:',temp)
print('changed array',e7)

original array: [0 1 2 3 4 5 6 7 8 9]
changed array [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [8]:
#第8题
e8=np.arange(10)
e8=e8.reshape(2,int(len(e8)/2))
print(e8)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
#第9题
a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)
e9=np.vstack((a,b))
print(e9)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [10]:
#第10题
a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)
e10=np.hstack((a,b))
print(e10)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [11]:
#第11题
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
e11=np.where(a==b)
print(e11[0])

[1 3 5 7]


In [12]:
#第12题
a=np.arange(15)
e12=np.where((a>=5) & (a<=10))
print(e12[0])

[ 5  6  7  8  9 10]


In [13]:
#第13题
a=np.arange(9).reshape(3,3)
e13=a[:,[1,0,2]]
print(e13)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [14]:
#第14题
a=np.arange(9).reshape(3,3)
e14=a[[1,0,2],:]
print(e14)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [15]:
#第15题
e15=np.random.rand(5,3)*5+5
print(e15)

[[8.88866832 7.67077321 5.26664526]
 [7.48746801 9.02966208 8.74791576]
 [9.02329056 8.47171808 7.57200892]
 [7.7919053  7.62495771 9.40630545]
 [9.75812934 8.19228508 6.18709231]]


In [16]:
#第16题
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
e16=a[np.where(a==b)]
e16=np.unique(e16)
print(e16)

[2 4]


In [17]:
#第17题
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
d=np.where(a==b)[0]
e17=np.delete(a,d)
print(e17)

[1 3 3 3 5 6]


In [18]:
#第18题
a=np.arange(9).reshape(3,3)
e18=a[::-1]
print(e18)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [19]:
#第19题
a=np.arange(9).reshape(3,3)
e19=a[:,::-1]
print(e19)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [20]:
#第20题
e20=np.arange(15)
r=np.random.randint(0,15)
e20[r]=44
print(e20)

[44  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [21]:
#第21题
a=np.array([1,2,3,2,3,4,3,4,5,6])
e21=np.unique(a,return_counts=True)
print(e21)

(array([1, 2, 3, 4, 5, 6]), array([1, 2, 3, 2, 1, 1], dtype=int64))


In [22]:
#第22题
a=np.arange(9).reshape(3,3)
e22=np.max(a,axis=0)
print(e22)

[6 7 8]


In [23]:
#第23题
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
e23=np.sum((a-b)**2)**0.5
print(e23)

12.529964086141668


In [24]:
#第24题
e24=np.arange(2,2+3*10,3)
print(e24)

[ 2  5  8 11 14 17 20 23 26 29]


In [3]:
#第25题
a_2d=np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d=np.array([1,2,3]).reshape(3,1)
e25=a_2d-b_1d
print(e25)

[[2 2 2]
 [2 2 2]
 [2 2 2]]
