## 内容：
##### 1&emsp;Pyhton函数
$\blacktriangleright$&emsp;np.zeros((m,n))&emsp;&emsp;&emsp;%生成全0的矩阵

In [3]:
import numpy as np
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

$\blacktriangleright$&emsp;np.ones((m,n))&emsp;&emsp;&emsp;%生成全1的矩阵

In [4]:
import numpy as np
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

$\blacktriangleright$&emsp;np.eye(n)&emsp;&emsp;&emsp;%生成单位阵

In [7]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

$\blacktriangleright$&emsp;np.random.rand(m,n)&emsp;&emsp;&emsp;%生成均匀分布的随机矩阵

In [8]:
import numpy as np
np.random.rand(3,3)

array([[0.26589148, 0.2247727 , 0.59877781],
       [0.89071185, 0.77106169, 0.13995027],
       [0.78985844, 0.04938128, 0.60795143]])

$\blacktriangleright$&emsp;np.diag([x])&emsp;&emsp;&emsp;%生成由向量元素构成的对角阵

In [10]:
import numpy as np
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

$\blacktriangleright$&emsp;np.tril(A)&emsp;&emsp;&emsp;%提取矩阵的下三角部分生成下三角阵

In [12]:
import numpy as np
np.tril(np.arange(1,10).reshape(3,3))

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

$\blacktriangleright$&emsp;np.triu(A)&emsp;&emsp;&emsp;%提取矩阵的上三角部分生成上三角阵

In [13]:
import numpy as np
np.triu(np.arange(1,10).reshape(3,3))

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

$\blacktriangleright$&emsp;matrix_rank(A)&emsp;&emsp;&emsp;%矩阵的秩

In [17]:
from numpy.linalg import *
matrix_rank(np.arange(1,10).reshape(3,3))

2

$\blacktriangleright$&emsp;det(A)&emsp;&emsp;&emsp;%方阵的行列式

In [18]:
from numpy.linalg import *
det(np.arange(1,10).reshape(3,3))

-9.51619735392994e-16

$\blacktriangleright$&emsp;inv(A)&emsp;&emsp;&emsp;%方阵的逆矩阵

In [19]:
from numpy.linalg import *
inv(np.arange(1,10).reshape(3,3))

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

$\blacktriangleright$&emsp;eig(A)&emsp;&emsp;&emsp;%方阵的特征值和特征向量

In [20]:
from numpy.linalg import *
eig(np.arange(1,10).reshape(3,3))

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

$\blacktriangleright$&emsp;norm(A,p)&emsp;&emsp;&emsp;%矩阵或向量的范数

In [22]:
from numpy.linalg import *
norm(np.arange(1,10).reshape(3,3),2)

16.84810335261421

$\blacktriangleright$&emsp;cond(A,p)&emsp;&emsp;&emsp;%矩阵的条件数

In [24]:
from numpy.linalg import *
cond(np.arange(1,10).reshape(3,3),2)

5.0522794445385096e+16

$\blacktriangleright$&emsp;lu(A)&emsp;&emsp;&emsp;%列主元LU分解，LU=PA

In [73]:
import numpy as np
from scipy.linalg import lu
(p,l,u)=lu(np.arange(1,10).reshape(3,3),permute_l=False)
print('p=','\n',p,'\n','L=','\n',l,'\n','U=','\n',u)

p= 
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] 
 L= 
 [[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]] 
 U= 
 [[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]


$\blacktriangleright$&emsp;cholesky(A)&emsp;&emsp;&emsp;%乔列斯基分解

In [35]:
import numpy as np
from scipy.linalg import cholesky
l=cholesky(np.mat('3 2 1;2 2 1;1 1 1'),lower=True)
print('L=',l)

L= [[1.73205081 0.         0.        ]
 [1.15470054 0.81649658 0.        ]
 [0.57735027 0.40824829 0.70710678]]


$\blacktriangleright$&emsp;hilbert(n)&emsp;&emsp;&emsp;%生成Hilbert矩阵

In [37]:
from scipy.linalg import hilbert
hilbert(4)

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.25      , 0.2       , 0.16666667, 0.14285714]])

$\blacktriangleright$&emsp;cond(A,1)&emsp;&emsp;&emsp;%1-范数条件数估计

In [38]:
from numpy.linalg import *
from scipy.linalg import hilbert
cond(hilbert(4),1)

28374.99999999729

##### 2&emsp;杜利脱尔分解

In [1]:
import numpy as np
def LU(A):
    m,n=A.shape
    L=np.zeros((n,n))
    U=np.zeros((n,n))
    for k in range(n):
        for r in range(n):
            U[k,r]=A[k,r]
            if k==r:
                L[k,r]=1
            if k<r:
                factor=A[r,k]/A[k,k]
                L[r,k]=factor
                for c in range(0,n):
                    A[r,c]=A[r,c]-factor*A[k,c]
                    U[r,c]=A[r,c]
    return [L,U]
A=np.mat('1 2 3;1 3 5;1 3 6')
LU(A)

[array([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]]), array([[1., 2., 3.],
        [0., 1., 2.],
        [0., 0., 1.]])]

##### 3&emsp;克洛托分解

In [105]:
import numpy as np
def Crout(a):
    cout=0
    m,n=a.shape
    if (m!=n):
        print("error")
    else:
        l=np.zeros((n,n))
        u=np.zeros((n,n))
        q1=0
        q2=0
        for i in range(n):
            l[i,0]=a[i,0]
            u[i,i]=1
        for j in range(1,n):
            u[0,j]=a[0,j]/l[0,0]
        for k in range(1,n):
            for i in range(k,n):
                for r in range(k): 
                    q1=q1+l[i,r]*u[r,k]
                    l[i,k]=a[i,k]-q1
                    q1=0
            for j in range(k+1, n):
                for r in range(k):
                    q2=q2+l[k,r]*u[r,j]
                    u[k,j]=(a[k,j]-q2)/l[k,k]
                    q2=0
    return(l,u)
a=np.mat('9 6 3;6 5 7;3 7 14')
Crout(a)

(array([[  9.,   0.,   0.],
        [  6.,   1.,   0.],
        [  3.,   5., -11.]]), array([[1.        , 0.66666667, 0.33333333],
        [0.        , 1.        , 5.        ],
        [0.        , 0.        , 1.        ]]))

##### 4&emsp;乔列斯基分解

In [108]:
import numpy as np
def cholesky(A):
    n=np.shape(A)[0]
    R=np.zeros((n,n))
    for j in range(n):
        for i in range(j,n):
            if i==j:
                s=0
                for k in range(j):
                    s=s+R[i,k]**2
                R[i,i]=np.sqrt(A[i,i]-s)
            else:
                s=0
                for k in range(j):
                    s=s+R[i,k]*R[j,k]
                R[i,j]=(A[i,j]-s)/R[j,j]
    return(R,R.T)

def back_subs(L,U,b):
    n=b.size
    x=np.zeros(n)
    c=np.zeros(n)

    c[0]=b[0]/L[0,0]
    for l in range(1,n):
        s=0
    for m in range(0,l):
        s=s+L[l,m]*c[m]
    c[l]=(b[l]-s)/L[l,l]

    for l in range(n-1,-1,-1):
        t=0
        for m in range(l+1,n):
            t=t+U[l,m]*x[m]
        x[l]=(c[l]-t)/U[l,l]
    return (x)

A=np.mat('3 2 1;2 2 1;1 1 1')
b=np.mat('3;2;2')
(L,U)=cholesky(A)
print(L,'\n',U,'\n',back_subs(L,U,b))

[[1.73205081 0.         0.        ]
 [1.15470054 0.81649658 0.        ]
 [0.57735027 0.40824829 0.70710678]] 
 [[1.73205081 1.15470054 0.57735027]
 [0.         0.81649658 0.40824829]
 [0.         0.         0.70710678]] 
 [ 1. -1.  2.]


##### 5&emsp;高斯消去法

In [145]:
import numpy as np
def gauss(a,b):
    n=b.size
    for k in range(n-1):
        for i in range(k+1,n):
            m=a[i,k]/a[k,k]
            for j in range(k,n):
                a[i,j]=a[i,j]-m*a[k,j]
            b[i]=b[i]-m*b[k]
    c=b
    x=np.ones(n)
    for l in range(n-1,-1,-1):
        for m in range(l+1,n):
            c[l]=c[l]-a[l,m]*x[m]
        x[l]=b[l]/a[l,l]
    return x
A=np.mat('1 2 3;1 3 5;1 3 6')
b0=np.mat('2;4;5')
gauss(A,b0)

array([-1.,  0.,  1.])

##### 6&emsp;列主元高斯消去法

In [10]:
import numpy as np
def v_gauss(a,b):
    n=b.size
    for k in range(n-1):
        d=np.argmax(a[k:,k])+k
        a[d,:],a[k,:]=a[k,:],a[d,:]
        b[d],b[k]=b[k],b[d]
        for i in range(k+1,n):
            m=a[i,k]/a[k,k]
            for j in range(k,n):
                a[i,j]=a[i,j]-m*a[k,j]
            b[i]=b[i]-m*b[k]
    c=b
    x=np.ones(n)
    for l in range(n-1,-1,-1):
        for m in range(l+1,n):
            c[l]=c[l]-a[l,m]*x[m]
        x[l]=b[l]/a[l,l]
    return x
A=np.mat('1 2 3;1 3 5;1 3 6')
b0=np.mat('2;4;5')
v_gauss(A,b0)

array([-1.,  0.,  1.])

## 练习
1.&emsp;用杜利脱尔分解求解下面的线性代数方程组
$$    \left(
    \begin{array}{ccc}
     1&2  &3 \\
     1&3  &5 \\
     1&3  &6 \\
    \end{array} \right)
    \left(
        \begin{array}{c}
         x_1\\
         x_2\\
         x_3\\
        \end{array} \right)=
        \left(
    \begin{array}{c}
     2\\
     4\\
     5\\
    \end{array} \right)$$

In [65]:
import numpy as np
from scipy.linalg import lu_solve
from scipy.linalg import lu_factor
a=lu_factor(np.mat('1 2 3;1 3 5;1 3 6'))
lu_solve(a,np.mat('2;4;5'))

array([[-1.],
       [ 0.],
       [ 1.]])

2.&emsp;用杜利脱尔分解求解下面的线性代数方程组
$$    \left(
    \begin{array}{cccc}
     5&7  &9  &10 \\
     6&8  &10  &9 \\
     7&10  &8  &7 \\
     5&7  &6  &5 \\
    \end{array} \right)
    \left(
        \begin{array}{c}
         x_1\\
         x_2\\
         x_3\\
         x_4\\
        \end{array} \right)=
        \left(
    \begin{array}{c}
     1\\
     1\\
     1\\
     1\\
    \end{array} \right)$$

In [66]:
import numpy as np
from scipy.linalg import lu_solve
from scipy.linalg import lu_factor
a=lu_factor(np.mat('5 7 9 10;6 8 10 9;7 10 8 7;5 7 6 5'))
lu_solve(a,np.mat('1;1;1;1'))

array([[ 20.],
       [-12.],
       [ -5.],
       [  3.]])

3.&emsp;用乔列斯基分解求解下面的线性代数方程组
$$    \left(
    \begin{array}{ccc}
     3&2  &1 \\
     2&2  &1 \\
     1&1  &1 \\
    \end{array} \right)
    \left(
        \begin{array}{c}
         x_1\\
         x_2\\
         x_3\\
        \end{array} \right)=
        \left(
    \begin{array}{c}
     3\\
     2\\
     2\\
    \end{array} \right)$$

In [64]:
import numpy as np
from scipy.linalg import cho_solve
from scipy.linalg import cho_factor
a=cho_factor(np.mat('3 2 1;2 2 1;1 1 1'),lower=True)
cho_solve(a,np.mat('3;2;2'))

array([[ 1.],
       [-1.],
       [ 2.]])

4.&emsp;用乔列斯基分解求解下面的线性代数方程组
$$    \left(
    \begin{array}{cccc}
     9&6  &3 \\
     6&5  &7 \\
     3&7  &14 \\
    \end{array} \right)
    \left(
        \begin{array}{c}
         x_1\\
         x_2\\
         x_3\\
        \end{array} \right)=
        \left(
    \begin{array}{c}
     6\\
     8\\
     10\\
    \end{array} \right)$$

In [1]:
print('该系数矩阵不是非负定的因此无法进行乔列斯基分解')

该系数矩阵不是非负定的因此无法进行乔列斯基分解


5.&emsp;分别用高斯消去法和列主元高斯消去法求解线性代数方程组
$$    \left(
    \begin{array}{cccc}
     4&-3  &3 \\
     3&2  &-6 \\
     1&-5  &3 \\
    \end{array} \right)
    \left(
        \begin{array}{c}
         x_1\\
         x_2\\
         x_3\\
        \end{array} \right)=
        \left(
    \begin{array}{c}
     4\\
     7\\
     3\\
    \end{array} \right)$$

In [13]:
import numpy as np
def gauss(a,b):
    n=b.size
    for k in range(n-1):
        for i in range(k+1,n):
            m=a[i,k]/a[k,k]
            for j in range(k,n):
                a[i,j]=a[i,j]-m*a[k,j]
            b[i]=b[i]-m*b[k]
    c=b
    x=np.ones(n)
    for l in range(n-1,-1,-1):
        for m in range(l+1,n):
            c[l]=c[l]-a[l,m]*x[m]
        x[l]=b[l]/a[l,l]
    return x
A=np.mat('4 -3 3;3 2 -6;1 -5 3')
b0=np.mat('4;7;3')
print('高斯消元法的结果为：',gauss(A,b0))
def v_gauss(a,b):
    n=b.size
    for k in range(n-1):
        d=np.argmax(a[k:,k])+k
        a[d,:],a[k,:]=a[k,:],a[d,:]
        b[d],b[k]=b[k],b[d]
        for i in range(k+1,n):
            m=a[i,k]/a[k,k]
            for j in range(k,n):
                a[i,j]=a[i,j]-m*a[k,j]
            b[i]=b[i]-m*b[k]
    c=b
    x=np.ones(n)
    for l in range(n-1,-1,-1):
        for m in range(l+1,n):
            c[l]=c[l]-a[l,m]*x[m]
        x[l]=b[l]/a[l,l]
    return x
A=np.mat('1 2 3;1 3 5;1 3 6')
b0=np.mat('2;4;5')
print('列主元高斯消元法的结果为：',v_gauss(A,b0))

高斯消元法的结果为： [ 1. -1. -1.]
列主元高斯消元法的结果为： [-1.  0.  1.]


## 作业：
#### **1.&emsp;两点边值问题离散方程的求解**
实验目的：使用直接法求解线性方程组。<br/>
实验内容：已知离散两点边值问题得到如下线性方程组
$$
    \left(
    \begin{array}{ccccc}
     4&-1  &0  &\ldots&0 \\
     -1&4  &-1&\ldots  &0 \\
     0&-1  &4  &\ldots&0 \\
     \vdots&\vdots&\vdots&\ddots&\vdots\\
     0&0  &\vdots&-1  &4 \\
    \end{array} \right)
    \left(
        \begin{array}{c}
         x_1\\
         x_2\\
         x_3\\
         \vdots\\
         x_n\\
        \end{array} \right)=
        \left(
    \begin{array}{c}
     100\\
     200\\
     200\\
     \vdots\\
     100\\
    \end{array} \right)
    $$
（1）编写利用克洛托分解求解上述线性方程组的程序Crout,其中$n=200$;<br/>
（2）编写利用平方根法求解上述线性方程组的程序cholesky，其中$n=200$;<br/>
（3）编写追赶法求解上述线性方程组的程序chase，其中$n=200$；<br/>
（4）试比较上述三种方法的优劣。

In [117]:
import numpy as np
from scipy.linalg import cho_solve
from scipy.linalg import cho_factor

#提取A,b
n=200
A=np.diag(4*np.ones(n))+np.diag(-np.ones(n-1),1)+np.diag(-np.ones(n-1),-1)
b=n*np.ones(n)
b[0]=n/2
b[n-1]=n/2

#克洛托分解
def Crout(a):
    n=np.size(a,0)
    L=np.zeros((n,n))
    U=np.zeros((n,n))
    for i in range(n):
        U[i,i]=1
        for j in range(i,n):
            s=0
            for k in range(i):
                s=s+L[j,k]*U[k,i]
            L[j,i]=a[j,i]-s
            if i!=j:
                s=0
                for k in range(i):
                    s=s+L[i,k]*U[k,j]
                U[i,j]=(a[i,j]-s)/L[i,i]
    return(L,U)
def back_subs(L,U,b):
    n=b.size
    x=np.zeros(n)
    c=np.zeros(n)
    c[0]=b[0]/L[0,0]
    for l in range(n):
        s=0
        for m in range(l):
            s=s+L[l,m]*c[m]
        c[l]=(b[l]-s)/L[l,l]

    for l in range(n-1,-1,-1):
        t=0
        for m in range(n-1,l,-1):
            t=t+U[l,m]*x[m]
        x[l]=(c[l]-t)/U[l,l]
    return(x)

[l,u]=Crout(A)
print('（1）克洛托分解法的结果为：\n',back_subs(l,u,b),'\n')

#平方根分解法
a=cho_factor(A,lower=True)
print('（2）平方根分解法的结果为：\n',cho_solve(a,b.T),'\n')

#追赶法
def chase(a,b,c,f):
    n=np.size(b)
    x=np.zeros(n)
    y=np.zeros(n)
    l=np.zeros(n)
    u=np.zeros(n-1)
    l[0]=b[0]
    y[0]=f[0]/l[0]
    u[0]=c[0]/l[0]
    for i in range(1,n-1):
        l[i]=b[i]-a[i-1]*u[i-1]
        y[i]=(f[i]-y[i-1]*a[i-1])/l[i]
        u[i]=c[i]/l[i]
    l[n-1]=b[n-1]-a[n-2]*u[n-2]
    y[n-1]=(f[n-1]-y[n-2]*a[n-2])/l[n-1]
    x[n-1]=y[n-1]
    for i in range(n-2,-1,-1):
        x[i]=y[i]-u[i]*x[i+1]
    return[x]
print('（3）追赶法的结果为：\n',chase(-np.ones(n-1),4*np.ones(n),-np.ones(n-1),b),'\n')

print('三者计算得到的结果相差不多，其中追赶法相对来说计算步骤最简单\n 但是追赶法只适用于对称三对角阵，条件最苛刻，而克洛托分解只需要矩阵可逆，平方根分解需要矩阵正定')

（1）克洛托分解法的结果为：
 [ 46.41016151  85.64064606  96.15242271  98.96904477  99.72375638
  99.92598074  99.9801666   99.99468566  99.99857603  99.99961845
  99.99989776  99.99997261  99.99999266  99.99999803  99.99999947
  99.99999986  99.99999996  99.99999999 100.         100.
 100.         100.         100.         100.         100.
 100.         100.         100.         100.         100.
 100.         100.         100.         100.         100.
 100.         100.         100.         100.         100.
 100.         100.         100.         100.         100.
 100.         100.         100.         100.         100.
 100.         100.         100.         100.         100.
 100.         100.         100.         100.         100.
 100.         100.         100.         100.         100.
 100.         100.         100.         100.         100.
 100.         100.         100.         100.         100.
 100.         100.         100.         100.         100.
 100.         100.         100. 

#### **2.&emsp;范德蒙德线性方程组的求解**
实验目的：条件数与高斯消去法的稳定性。<br/>
实验内容：考虑范德蒙德线性方程组
$$
    \left(
    \begin{array}{ccccc}
     1&x_0  &x_0^2  &\ldots&x_0^n \\
     1&x_1  &x_1^2&\ldots  &x_1^n \\
     1&x_2  &x_2^2  &\ldots&x_2^n \\
     \vdots&\vdots&\vdots&\ddots&\vdots\\
     1&x_n  &x_n^2&\ldots  &x_n^n \\
    \end{array} \right)
    \left(
        \begin{array}{c}
         z_0\\
         z_1\\
         z_2\\
         \vdots\\
         z_n\\
        \end{array} \right)=
        \left(
    \begin{array}{c}
     \sum\limits_{i=0}^nx_0^i\\
     \sum\limits_{i=0}^nx_1^i\\
     \sum\limits_{i=0}^nx_2^i\\
     \vdots\\
     \sum\limits_{i=0}^nx_n^i\\
    \end{array} \right)
    $$
其中。$x_k=1+0.1k$，$k=0,1,\cdots n$，<br/>
（1）对$n=2,5,8$，计算系数矩阵的条件数；随$n$增大，矩阵性态如何变化？<br/>
（2）对$n=5$，解该方程组；设系数矩阵的最后一个元素有扰动$10^{-4}$，再求解该方程组；<br/>
（3）计算（2）中扰动的相对误差和解的相对误差，分析它们与条件数的关系；<br/>
（4）你能由此解释为什么不用插值函数存在定理中的方法直接求插值函数，而要用拉格朗日插值或牛顿插值法吗？

In [17]:
import numpy as np
from scipy import *
from scipy import linalg

print('（1）')
for n in range(2,9,3):
    x=np.zeros(n+1)
    for k in range(0,n+1):
        x[k]=1+0.1*k
    X=vander(x,increasing=True)
    print('n=',n,'时的条件数为',np.linalg.cond(X))
print('由结果看出，随n增大条件数以极高速度增长')
    
print('（2）')
x=np.zeros(6)
b=np.zeros(6)
for k in range(0,6):
    x[k]=1+0.1*k
X=vander(x,increasing=True)
for i in range(0,6):
    b[i]=np.sum(X[i,0:])
x0=linalg.solve(X,b)
print('施加扰动前，方程组的解为',x0)
X[5,5]=X[5,5]+10**-4
x1=linalg.solve(X,b)
print('施加扰动后，方程组的解为',x1)

print('（3）')
c=np.linalg.cond(X)
print('条件数为',c)
print('扰动的相对误差为',np.abs(10**-4/(X[5,5]+10**-4))/36)
print('解的相对误差为',np.sum(np.abs((x1-x0)/x0))/6)
print('猜测条件数与扰动的相对误差的乘积与解的相对误差是一个数量级，故条件数越大解的误差越大')

print('（4）')
print('因为当矩阵条件数过大时，插值函数存在定理中的方法误差过大')

（1）
n= 2 时的条件数为 1104.400098300591
n= 5 时的条件数为 5594498.784355135
n= 8 时的条件数为 22739097630.89334
由结果看出，随n增大条件数以极高速度增长
（2）
施加扰动前，方程组的解为 [1. 1. 1. 1. 1. 1.]
施加扰动后，方程组的解为 [ 1.1848      0.21904615  2.31538462 -0.10384615  1.46153846  0.92307692]
（3）
条件数为 5209064.502007606
扰动的相对误差为 3.657882627325408e-07
解的相对误差为 0.6539076923059897
猜测条件数与扰动的相对误差的乘积与解的相对误差是一个数量级，故条件数越大解的误差越大
（4）
因为当矩阵条件数过大时，插值函数存在定理中的方法误差过大


#### **3.&emsp;线性方程组的性态与条件数估计**
实验目的：线性方程组的性态、条件数估计。<br/>
实验内容：<br/>
（1）构造非奇异矩阵$A$和右端向量$b$，使得线性方程组$Ax=b$可以精确求解；再引入系数矩阵和有段向量的扰动$\Delta A$和$\Delta b$，使得$\parallel\Delta A\parallel$和$\parallel\Delta b\parallel$充分小。设方程$Ax=b$的解为$x$，方程$(A+\Delta)\hat{x}=b+\Delta b$的解为$\hat{x}$，以向量1-范数，给出$\dfrac{\parallel\Delta x\parallel}{\parallel x\parallel}=\dfrac{\parallel\hat{x}-x\parallel}{\parallel x\parallel}$的计算结果；<br/>
（2）选择一系列维数递增的矩阵$A$（可以是随机生成的），比较函数cond所需机器时间的差别。考虑若干逆是已知的矩阵，借助函数eig给出$\text{cond}_2(A)$的数值，并将它与函数$\text{cond}(A,2)$所得到的结果进行比较；<br/>
（3）利用函数condset给出矩阵$A$条件数的估计，并应用如下结论
$$\dfrac{\parallel\Delta x\parallel}{\parallel x\parallel}\le\dfrac{\text{cond}(A)}{1-\parallel A^{-1}\parallel\parallel\Delta A\parallel}\left(\dfrac{\parallel\Delta A\parallel}{\parallel A\parallel}+\dfrac{\parallel\Delta b\parallel}{\parallel b\parallel}\right)$$
分析$\dfrac{\parallel\Delta x\parallel}{\parallel x\parallel}$的理论估计，并与（1）给出的计算结果进行比较，分析所得结果。注意如果给出了$\text{cond}(A)$和$\parallel A\parallel$的估计，则可以容易给出$\parallel A^{-1}\parallel$的估计。<br/>
（4）估计著名的Hilbert矩阵的条件数。

In [16]:
import numpy as np
from scipy import linalg
import time
print('（1）')
A0=np.random.randint(0,37,(6,6))
b0=np.random.randint(0,7,(6,1))
x=linalg.solve(A0,b0)
dA=A0+np.random.rand(6,6)*10**-5
db=b0+np.random.rand(6,1)*10**-5
dx=linalg.solve(dA,db)
result=np.linalg.norm(dx-x,1)/np.linalg.norm(x,1)
print('A为\n',A0,'\n b为\n',b0)
print('扰动后A为\n',dA,'\n 扰动后b为\n',db)
print('x为\n',x,'\n 扰动后x为\n',dx)
print('计算结果为\n',result)

print('（2）')
for n in range(10,101,10):
    A=np.random.randint(0,1+n**2,(n,n))
    start=time.time()
    c=np.linalg.cond(A,1)
    end=time.time()
    print('维数n为',n,'时的机器运行时间为',end-start)
    
    AA=np.dot(A,A.T)
    AI=np.dot(np.linalg.inv(A),np.linalg.inv(A).T)
    fa=np.max(np.linalg.eig(AA)[0])
    fai=np.max(np.linalg.eig(AI)[0])
    a=np.sqrt(fa)*np.sqrt(fai)
    b=np.linalg.cond(A,2)
    print('此时eig得到的条件数为',a,'cond得到的条件数为',b,'\n')
print('可以发现eig得到的条件数在阶数较小时与cond得到的相似，但阶数较高以后eig得到的条件数开始出现比较大的误差')
    
print('（3）')
e1=np.linalg.cond(A0)/(1-np.linalg.norm(np.linalg.inv(A0),1)*np.linalg.norm(dA-A0,1))
e2=np.linalg.norm(dA-A0,1)/np.linalg.norm(A0,1)+np.linalg.norm(db-b0,1)/np.linalg.norm(b0,1)
print('理论估计的上界为',e1*e2,'\n 实际结果为',result)

print('（4）')
for n in range(10,101,10):
    H=linalg.hilbert(n)
    print('阶数n为',n,'时条件数为',np.linalg.cond(H),'\n')

（1）
A为
 [[19  8 32 35 16  8]
 [ 4 36 33 11  6 33]
 [17 24 36  6 11 13]
 [36 21 25 13  1  0]
 [14 31  2  2  4 16]
 [ 9 20 20 31 20 30]] 
 b为
 [[0]
 [6]
 [2]
 [4]
 [5]
 [3]]
扰动后A为
 [[1.90000016e+01 8.00000482e+00 3.20000022e+01 3.50000019e+01
  1.60000015e+01 8.00000735e+00]
 [4.00000877e+00 3.60000078e+01 3.30000012e+01 1.10000060e+01
  6.00000581e+00 3.30000004e+01]
 [1.70000044e+01 2.40000056e+01 3.60000039e+01 6.00000391e+00
  1.10000015e+01 1.30000087e+01]
 [3.60000000e+01 2.10000041e+01 2.50000074e+01 1.30000058e+01
  1.00000966e+00 8.63038655e-06]
 [1.40000052e+01 3.10000023e+01 2.00000257e+00 2.00000074e+00
  4.00000180e+00 1.60000093e+01]
 [9.00000435e+00 2.00000080e+01 2.00000014e+01 3.10000055e+01
  2.00000056e+01 3.00000006e+01]] 
 扰动后b为
 [[1.98529372e-07]
 [6.00000797e+00]
 [2.00000519e+00]
 [4.00000901e+00]
 [5.00000145e+00]
 [3.00000368e+00]]
x为
 [[ 0.10633519]
 [ 0.04725312]
 [-0.03097104]
 [ 0.01227049]
 [-0.20562273]
 [ 0.18164704]] 
 扰动后x为
 [[ 0.10633609]
 [ 0.04725213